name: dargon2_flutter_desktop
description: The desktop (macos, windows, and linux) implementation of dargon2_flutter
version: 3.2.0
homepage: https://github.com/tmthecoder/dargon2/
repository: https://github.com/tmthecoder/dargon2/blob/main/dargon2_flutter/dargon2_flutter_desktop

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dargon2_core: '^2.1.0'
  dargon2_flutter_platform_interface: '^3.2.0'
  dargon2_interface: '^1.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: dargon2_flutter
    platforms:
      linux:
        pluginClass: Dargon2FlutterDesktopPlugin
        ffiPlugin: true
      macos:
        pluginClass: Dargon2FlutterDesktopPlugin
        ffiPlugin: true
      windows:
        pluginClass: Dargon2FlutterDesktopPlugin
        ffiPlugin: true

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
