name: dargon2_flutter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: dargon2_flutter/dargon2_flutter/example

jobs:
  test_android:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
         java-version: '17'
         distribution: 'zulu'
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33-x64
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Upgrade flutter
        run: flutter upgrade
      - name: Use Test Pubspec Files
        run: |
          rm ../pubspec.yaml
          rm ../../dargon2_flutter_web/pubspec.yaml
          rm ../../dargon2_flutter_mobile/pubspec.yaml
          rm ../../dargon2_flutter_desktop/pubspec.yaml
          rm ../../dargon2_flutter_platform_interface/pubspec.yaml          
          rm ../../../dargon2_core/pubspec.yaml
          mv ../pubspec.test.yaml ../pubspec.yaml          
          mv ../../dargon2_flutter_web/pubspec.test.yaml ../../dargon2_flutter_web/pubspec.yaml
          mv ../../dargon2_flutter_mobile/pubspec.test.yaml ../../dargon2_flutter_mobile/pubspec.yaml
          mv ../../dargon2_flutter_desktop/pubspec.test.yaml ../../dargon2_flutter_desktop/pubspec.yaml
          mv ../../dargon2_flutter_platform_interface/pubspec.test.yaml ../../dargon2_flutter_platform_interface/pubspec.yaml          
          mv ../../../dargon2_core/pubspec.test.yaml ../../../dargon2_core/pubspec.yaml
      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          working-directory: dargon2_flutter/dargon2_flutter/example
          script: flutter test integration_test/

  test_ios:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Upgrade flutter
        run: flutter upgrade
      - name: List Simulators
        run: xcrun simctl list devices
      - name: Start Simulator
        run: |
          UDID=$(
          xcrun simctl list devices | grep "iPhone 15 (" | awk -F"[()]" '{print $2}' | awk 'NR==1{print $1}'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: Use Test Pubspec Files
        run: |
          rm ../pubspec.yaml
          rm ../../dargon2_flutter_web/pubspec.yaml
          rm ../../dargon2_flutter_mobile/pubspec.yaml
          rm ../../dargon2_flutter_desktop/pubspec.yaml
          rm ../../dargon2_flutter_platform_interface/pubspec.yaml          
          rm ../../../dargon2_core/pubspec.yaml
          mv ../pubspec.test.yaml ../pubspec.yaml          
          mv ../../dargon2_flutter_web/pubspec.test.yaml ../../dargon2_flutter_web/pubspec.yaml
          mv ../../dargon2_flutter_mobile/pubspec.test.yaml ../../dargon2_flutter_mobile/pubspec.yaml
          mv ../../dargon2_flutter_desktop/pubspec.test.yaml ../../dargon2_flutter_desktop/pubspec.yaml
          mv ../../dargon2_flutter_platform_interface/pubspec.test.yaml ../../dargon2_flutter_platform_interface/pubspec.yaml          
          mv ../../../dargon2_core/pubspec.test.yaml ../../../dargon2_core/pubspec.yaml          
      - name: Run Integration Tests
        run: flutter test integration_test/

  test_web:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Use Test Pubspec Files
        run: |
          rm ../pubspec.yaml
          rm ../../dargon2_flutter_web/pubspec.yaml
          rm ../../dargon2_flutter_mobile/pubspec.yaml
          rm ../../dargon2_flutter_desktop/pubspec.yaml
          rm ../../dargon2_flutter_platform_interface/pubspec.yaml          
          rm ../../../dargon2_core/pubspec.yaml
          mv ../pubspec.test.yaml ../pubspec.yaml          
          mv ../../dargon2_flutter_web/pubspec.test.yaml ../../dargon2_flutter_web/pubspec.yaml
          mv ../../dargon2_flutter_mobile/pubspec.test.yaml ../../dargon2_flutter_mobile/pubspec.yaml
          mv ../../dargon2_flutter_desktop/pubspec.test.yaml ../../dargon2_flutter_desktop/pubspec.yaml
          mv ../../dargon2_flutter_platform_interface/pubspec.test.yaml ../../dargon2_flutter_platform_interface/pubspec.yaml          
          mv ../../../dargon2_core/pubspec.test.yaml ../../../dargon2_core/pubspec.yaml          
      - run: flutter pub get
      - run: chromedriver --port=4444 &
      - run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/argon2_ffi_test.dart -d web-server

  test_desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
#          - os: macos-latest
#            FLUTTER_DEVICE: macos
#            FLUTTER_CHANNEL: stable
#          - os: ubuntu-latest
#            FLUTTER_DEVICE: linux
#            FLUTTER_CHANNEL: beta
          - os: windows-latest
            FLUTTER_DEVICE: windows
            FLUTTER_CHANNEL: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ matrix.FLUTTER_CHANNEL }}
      - name: Enable Flutter Desktop
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-windows-desktop
      - if: matrix.os == 'ubuntu-latest'
        name: Install Ninja (Ubuntu Only)
        run: sudo apt install -y ninja-build libgtk-3-dev clang
      - name: Use Test Pubspec Files
        run: |
          rm ../pubspec.yaml
          rm ../../dargon2_flutter_web/pubspec.yaml
          rm ../../dargon2_flutter_mobile/pubspec.yaml
          rm ../../dargon2_flutter_desktop/pubspec.yaml
          rm ../../dargon2_flutter_platform_interface/pubspec.yaml          
          rm ../../../dargon2_core/pubspec.yaml
          mv ../pubspec.test.yaml ../pubspec.yaml          
          mv ../../dargon2_flutter_web/pubspec.test.yaml ../../dargon2_flutter_web/pubspec.yaml
          mv ../../dargon2_flutter_mobile/pubspec.test.yaml ../../dargon2_flutter_mobile/pubspec.yaml
          mv ../../dargon2_flutter_desktop/pubspec.test.yaml ../../dargon2_flutter_desktop/pubspec.yaml
          mv ../../dargon2_flutter_platform_interface/pubspec.test.yaml ../../dargon2_flutter_platform_interface/pubspec.yaml          
          mv ../../../dargon2_core/pubspec.test.yaml ../../../dargon2_core/pubspec.yaml          
      - name: Run Integration Tests
        run: flutter test -d ${{ matrix.FLUTTER_DEVICE }} integration_test/

