name: dargon2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: dargon2

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - name: Use Test Pubspec Files
      run: |
        rm pubspec.yaml
        rm ../dargon2_core/pubspec.yaml
        mv pubspec.test.yaml pubspec.yaml
        mv ../dargon2_core/pubspec.test.yaml ../dargon2_core/pubspec.yaml
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: dart --enable_deprecated_wait_for test
